# @name login
POST http://localhost:8777/metrics/service/worksmartlogin/login/0?seq=1
content-type: application/json

{
    "app_code_token":"11"
}



###
@authToken = {{login.response.body.apptoken}}

POST http://localhost:8777/metrics/service/metricsdata/list/0?seq=1 HTTP/1.1
apptoken: {{authToken}}
content-type: application/json

{
    "startIndex":1,
    "length":10
}